theme: jekyll-theme-slate
title: GENEVA Code: Pre-Supernovae
description: This site regroup various informations about the implementation of Timmes EOS, the acceleration term and the nuclear reaction network.
